apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  project: default
  source:
    repoURL: 'git@github.com:Ubunfu/blog-ops.git'
    path: dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

