apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog-web
spec:
  selector:
    matchLabels:
      app: blog-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80